spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: dbuser
    password: dbuserpassword
    url: jdbc:h2:mem:default
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/master-change-log.xml
    enabled: true
server:
  port: 8082